apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.busyboxNamespace }}
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: {{ .Values.busyboxNamespace }}
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["/bin/sh"]
    args:
    - "-c"
    - >
      while true; do
        curl http://{{ .Values.nginxServiceName }};
        echo "";  # For readability in output
        sleep 10;
      done
