apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nginxNamespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.nginxNamespace }}
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginxServiceName }}
  namespace: {{ .Values.nginxNamespace }}
spec:
  ports:
  - port: 80
  selector:
    app: nginx
