apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-tls-dep
  labels:
    app.kubernetes.io/name: ingresstls
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingresstls
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingresstls
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/nginx/certs
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-certs