kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-lab-cluster
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  disableDefaultCNI: false  # Use Kind's default CNI
  # Optionally, specify other networking configs if needed
