name: Deploy Kubernetes Cluster lab(Windows)

on:
  workflow_dispatch:
    inputs:
      lab_number:
        description: 'Lab Number (e.g., lab1, lab2, lab3)'
        required: true
        default: 'lab1'

jobs:
  deploy-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install kubectl using Chocolatey
        run: choco install kubernetes-cli -y

      - name: Deploy Kubernetes cluster
        run: python kcdctl.py deploy ${{ github.event.inputs.lab_number }}

      - name: Get cluster info
        run: |
          kubectl get nodes
          kubectl get namespace
          kubectl get pods
