name: Deploy Kubernetes Cluster lab01

on: workflow_dispatch

jobs:
  deploy-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'    
        
      - name: Deploy Kubernetes cluster
        run: python kcdctl.py deploy lab1
      
      - name: Install kubectl
        run: |
          sudo snap install kubectl --classic
      
      - name: Get cluster info
        run: |
          kubectl get nodes
          kubectl get namespace
          kubectl get pods


